# Generated by Django 2.1.8 on 2019-04-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
    ]
